### ISSUE TITLE
Unclear comment about charging being both enabled and disabled at 5%

### ISSUE THREAD

**Issue by stephendonner** [gmierz/powerusage-android#2]
hey Greg - thanks again for all this hard work!

I'm starting to go through it, and just read https://github.com/gmierz/powerusage-android/blob/4cb73c65cac7b73bc5b0070fcb42407848c7299b/android_os_baseline_by_percent.py#L38 which isn't clear to me.  Would you mind clarifying/fixing the comment?

Cheers!

**Comment by gmierz** [comment]
Yup no problem, I'll have it fixed shortly.

**Comment by gmierz** [comment]
Clarified in this commit: https://github.com/gmierz/powerusage-android/commit/859bf24426db53f7318ec5f768188ab09b025809

You can reopen this issue if you find that it's still unclear.
