### ISSUE TITLE
Migrate/transfer ownership of repo to Mozilla GitHub org

### ISSUE THREAD

**Issue by stephendonner** [gmierz/powerusage-android#9]
Migrate this repo to the Mozilla GitHub account/org, so we can take advantage of free Travis CI, start linting, etc.,

https://wiki.mozilla.org/GitHub#Forking_vs_Transferring

**Comment by gmierz** [comment]
I'll do this on Monday when more people are online (so it doesn't block anyone).

**Comment by gmierz** [comment]
I don't have the required permissions to initiate the transfer. @stephendonner are you are "org admin" that can initiate the transfer?

**Comment by stephendonner** [comment]
> I don't have the required permissions to initiate the transfer. @stephendonner are you an "org admin" that can initiate the transfer?

I'm not, no; but if you make me a co-owner of this repo (I think?) I should be able to start the transfer-(request) process.

**Comment by stephendonner** [comment]
It's been migrated[0], with you and I, Greg, made Admins[1]!

[0] https://github.com/mozilla/powerusage-android
[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1543210

We can later tweak the "forked from..." bit.

<img width="1374" alt="Screen Shot 2019-04-09 at 3 34 16 PM" src="https://user-images.githubusercontent.com/387249/55839560-2e259d00-5add-11e9-9a4c-39a4fd77dfab.png">
